[package]
name = "studio"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/peudomi/gpui.git" }
gpui-base = { git = "https://github.com/peudomi/gpui-component" }
gpui_platform = { git = "https://github.com/peudomi/gpui.git" }
raw-window-handle = "0.6"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
